version: '3'

services:
  retrospeaks:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: retrospeaksDB
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - data:/var/lib/retrospeaks/mysql
    ports:
      - "3306:3306"

volumes:
  data:


