version: '3'

services:
  retrospeaksMariaDB:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: retrospeaksDB
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mariaDB_data_container:/var/lib/retrospeaks/mysql
    ports:
      - "3306:3306"

volumes:
  mariaDB_data_container:


