version: '3'
services:
  retrospeaksMongoDB:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "3307:27017"

    volumes:
      - mongoDB_data_container:/data/db

volumes:
  mongoDB_data_container: